### ISSUE TITLE
GPU is not loaded during training..

### ISSUE THREAD

**Issue by YanAwithU** [pythonlessons/TensorFlow-2.x-YOLOv3#45]
Hi! I wanna train yolov3-tiny custom model.
I has google cloud platform instance and here is environment.
```
OS : Ubuntu 18.04
GPU : Tesla K80 
cuda : 10.0
cuDNN : 7.4.2
nvidia driver version : 450
Tensorflow version : 2.0.0 gpu
```

nvidia-smi and nvcc are successfully worked.
Gpu list is successfully loaded on python prompt.
But it can not on train.py
What happened??

Here is error.
`tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected`

Here is result that I load gpu on python prompt
```
Python 3.7.9 (default, Sep  5 2020, 20:35:59) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
/usr/local/lib/python3.7/site-packages/pandas/compat/__init__.py:120: UserWarning: Could not import the lzma module
. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
>>> gpus=tf.config.experimental.list_physical_devices('GPU')
2020-09-06 00:22:39.765471: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dyn
amic library libcuda.so.1
2020-09-06 00:22:42.146957: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read 
from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-06 00:22:42.147888: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties
: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:04.0
2020-09-06 00:22:42.148244: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dyn
amic library libcudart.so.10.0
2020-09-06 00:22:42.150090: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dyn
amic library libcublas.so.10.0
2020-09-06 00:22:42.151637: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dyn
amic library libcufft.so.10.0
2020-09-06 00:22:42.151987: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dyn
amic library libcurand.so.10.0
2020-09-06 00:22:42.153944: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dyn
amic library libcusolver.so.10.0
2020-09-06 00:22:42.155584: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dyn
amic library libcusparse.so.10.0
2020-09-06 00:22:42.161431: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dyn
amic library libcudnn.so.7
2020-09-06 00:22:42.161581: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read 
from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-06 00:22:42.163090: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1006] successful NUMA node read 
from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2020-09-06 00:22:42.163816: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
```
When I tried to run train.py
```
root@instance-1:/home/TensorFlow-2.x-YOLOv3# python3 train.py
/usr/local/lib/python3.7/site-packages/pandas/compat/__init__.py:120: UserWarning: Could not import the lzma module
. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
2020-09-06 00:24:33.931352: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dyn
amic library libcuda.so.1
2020-09-06 00:24:36.422085: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR
_NO_DEVICE: no CUDA-capable device is detected
2020-09-06 00:24:36.422153: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic i
nformation for host: instance-1
```

I think lzma module issue does not matter.

**Comment by YanAwithU** [comment]
This problem is not solved yet??? @pythonlessons

**Comment by pythonlessons** [comment]
I am on vacation now, try to install TensorFlow 2.3

**Comment by YanAwithU** [comment]
> I am on vacation now, try to install TensorFlow 2.3

Sorry for calling during vacation.. I'll try soon!

**Comment by naitfox** [comment]
Hello, my config is:
Ubuntu 18.04
GTX 1660 Ti
Nvidia r418.151
CUDA 10.1
cudnn 7.6.5

I tried with both TF 2.2 and TF 2.3

This is recommendedfrom the tensorflow website. 
So I am also encountering similar problem:

(base) swastik@p3:~/Documents/dock/TensorFlow-2.x-YOLOv3$ python train.py
2020-09-08 02:38:43.903271: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2020-09-08 02:38:44.680134: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2020-09-08 02:38:44.684673: E tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-09-08 02:38:44.684691: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: p3
2020-09-08 02:38:44.684695: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: p3
2020-09-08 02:38:44.684754: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 418.152.0
2020-09-08 02:38:44.684783: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 418.152.0
2020-09-08 02:38:44.684787: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 418.152.0
2020-09-08 02:38:44.685340: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-09-08 02:38:44.707188: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2599990000 Hz
2020-09-08 02:38:44.707755: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55db94287a00 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-08 02:38:44.707778: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
skipping conv2d_74
skipping conv2d_66
skipping conv2d_58



I tried to use GPU with tensorflow otherwise and it worked. But here it is showing that it cant detect CUDA-capable device. Pls help.

**Comment by FussnerS** [comment]
I was having a similar problem. I added from tensorflow.python.client import device_lib and then have to print devices and it works for some reason.

import os
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
import tensorflow as tf
gpus = tf.config.experimental.list_physical_devices('GPU')
    print(f'GPUs {gpus}')
    if len(gpus) > 0:
        try:
            tf.config.experimental.set_memory_growth(gpus[0], True)
        except RuntimeError:
            pass

**Comment by YanAwithU** [comment]
> I was having a similar problem. I added from tensorflow.python.client import device_lib and then have to print devices and it works for some reason.
> 
> import os
> _from tensorflow.python.client import device_lib_
> _print(device_lib.list_local_devices())_
> os.environ['CUDA_VISIBLE_DEVICES'] = **'-1'**
> import tensorflow as tf
> gpus = tf.config.experimental.list_physical_devices('GPU')
> _print(f'GPUs {gpus}')_
> if len(gpus) > 0:
> try:
> tf.config.experimental.set_memory_growth(gpus[0], True)
> except RuntimeError:
> pass

I tried this code on my environment commented above, successfully worked!
I add 3 lines and changed 1 parameter. I expressed that above quotation(adding is italic, changing is bold).
Thanks for your advice!

**Comment by YanAwithU** [comment]
@FussnerS Do you figure out what is the reason?? Can you explain that?

**Comment by FussnerS** [comment]
> 
> 
> @FussnerS Do you figure out what is the reason?? Can you explain that?

I really have no idea why it works or where found the recommendation. It's kind of weird in my opinion. Even removing the "print(device_lib.list_local_devices())" makes it not work.

**Comment by YanAwithU** [comment]
I think that loading devices at least once by force through the imported library matters. Anyway,  I really want to thank you for your help.

**Comment by wzhao82** [comment]
Maybe edit: os.environ['CUDA_VISIBLE_DEVICES'] = '0'
